#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Regenerate first-party SPIR-V with explicitly selected, pinned SDK tools."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()
def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--glslang", type=Path, required=True)
    parser.add_argument("--spirv-val", type=Path, required=True)
    args = parser.parse_args()
    pins = json.loads((ROOT / "toolchains" / "render-dependencies.json").read_text())
    expected = pins["shader_tools"]["verified_windows_binaries"]
    if digest(args.glslang) != expected["glslang_sha256"] or digest(args.spirv_val) != expected["spirv_val_sha256"]:
        raise RuntimeError("Shader tool bytes differ from the verified SDK binaries; review new platform tool pins before regeneration")
    output = ["// SPDX-License-Identifier: Apache-2.0", "// Generated by tools/generate_render_shaders.py; see shaders/provenance.json.", "#pragma once", "#include <cstdint>", "namespace ow::render::shaders {"]
    manifest = {"schema_version": 1, "sdk_version": "1.4.357.0", "target_environment": "vulkan1.3", "tools": {"glslang_sha256": digest(args.glslang), "spirv_val_sha256": digest(args.spirv_val)}, "shaders": {}}
    with tempfile.TemporaryDirectory() as temporary:
        for stage, symbol in (("vert", "vertex"), ("frag", "fragment")):
            source = ROOT / "shaders" / ("world_cube." + stage)
            binary = Path(temporary) / (stage + ".spv")
            # Keep compiler output private; public provenance contains relative input names only.
            subprocess.run([str(args.glslang.resolve()), "-V", "--target-env", "vulkan1.3", "-o", str(binary), str(source)], check=True, capture_output=True)
            subprocess.run([str(args.spirv_val.resolve()), "--target-env", "vulkan1.3", str(binary)], check=True, capture_output=True)
            data = binary.read_bytes()
            words = struct.unpack("<" + "I" * (len(data)//4), data)
            output.append("inline constexpr std::uint32_t " + symbol + "[] = {")
            for index in range(0, len(words), 8):
                output.append("  " + ", ".join(f"0x{word:08x}U" for word in words[index:index+8]) + ",")
            output.append("};")
            manifest["shaders"][stage] = {"source": source.relative_to(ROOT).as_posix(), "source_sha256": digest(source), "spirv_sha256": hashlib.sha256(data).hexdigest(), "word_count": len(words), "validation": "passed"}
    output.append("}  // namespace ow::render::shaders")
    header = ROOT / "src" / "world_cube_spirv.hpp"
    header.write_text("\n".join(output) + "\n", encoding="utf-8", newline="\n")
    manifest["header_sha256"] = digest(header)
    (ROOT / "shaders" / "provenance.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    print("First-party shaders generated and independently validated.")
if __name__ == "__main__":
    main()
