# SPDX-License-Identifier: Apache-2.0
set(OW_RENDER_DEPS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/.cache/render-deps" CACHE PATH "Explicitly provisioned graphics sources")
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/toolchains/render-dependencies.json" render_pins)
foreach(dependency IN ITEMS sdl vulkan_headers)
  foreach(field IN ITEMS archive directory sha256 source_manifest_sha256)
    string(JSON ${field} GET "${render_pins}" source_archives ${dependency} ${field})
  endforeach()
  if(NOT EXISTS "${OW_RENDER_DEPS_DIR}/${archive}" OR NOT EXISTS "${OW_RENDER_DEPS_DIR}/${dependency}-files.json")
    message(FATAL_ERROR "Run Python tools/provision_render.py before optional configuration; CMake never downloads graphics dependencies.")
  endif()
  file(SHA256 "${OW_RENDER_DEPS_DIR}/${archive}" actual_archive)
  file(SHA256 "${OW_RENDER_DEPS_DIR}/${dependency}-files.json" actual_manifest)
  if(NOT actual_archive STREQUAL sha256 OR NOT actual_manifest STREQUAL source_manifest_sha256)
    message(FATAL_ERROR "Graphics dependency archive or source-manifest integrity mismatch.")
  endif()
  file(READ "${OW_RENDER_DEPS_DIR}/${dependency}-files.json" source_manifest)
  string(JSON count LENGTH "${source_manifest}")
  file(GLOB_RECURSE present_sources LIST_DIRECTORIES FALSE RELATIVE "${OW_RENDER_DEPS_DIR}/${directory}" "${OW_RENDER_DEPS_DIR}/${directory}/*")
  list(LENGTH present_sources present_count)
  if(NOT present_count EQUAL count)
    message(FATAL_ERROR "Pinned graphics source tree has unexpected or missing files.")
  endif()
  math(EXPR last "${count}-1")
  foreach(index RANGE ${last})
    string(JSON path MEMBER "${source_manifest}" ${index})
    string(JSON expected GET "${source_manifest}" "${path}")
    if(NOT EXISTS "${OW_RENDER_DEPS_DIR}/${directory}/${path}")
      message(FATAL_ERROR "Pinned graphics source is incomplete; rerun explicit provisioning.")
    endif()
    file(SHA256 "${OW_RENDER_DEPS_DIR}/${directory}/${path}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "Pinned graphics source differs from its reviewed archive.")
    endif()
  endforeach()
  set(OW_${dependency}_SOURCE "${OW_RENDER_DEPS_DIR}/${directory}")
endforeach()
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/shaders/provenance.json" shader_provenance)
string(JSON expected GET "${shader_provenance}" header_sha256)
file(SHA256 "${CMAKE_CURRENT_SOURCE_DIR}/src/world_cube_spirv.hpp" actual)
if(NOT actual STREQUAL expected)
  message(FATAL_ERROR "Shader words differ from their validated provenance.")
endif()
foreach(stage IN ITEMS vert frag)
  string(JSON source GET "${shader_provenance}" shaders ${stage} source)
  string(JSON expected GET "${shader_provenance}" shaders ${stage} source_sha256)
  file(SHA256 "${CMAKE_CURRENT_SOURCE_DIR}/${source}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Shader source differs from its validated provenance.")
  endif()
endforeach()
enable_language(C)
if(NOT CMAKE_C_COMPILER_ID STREQUAL CMAKE_CXX_COMPILER_ID OR NOT CMAKE_C_COMPILER_VERSION VERSION_EQUAL CMAKE_CXX_COMPILER_VERSION)
  message(FATAL_ERROR "Optional SDL must use the same pinned C and C++ compiler family/version.")
endif()
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
foreach(option IN ITEMS SDL_TEST_LIBRARY SDL_TESTS SDL_EXAMPLES SDL_AUDIO SDL_JOYSTICK SDL_HAPTIC SDL_GAMEPAD SDL_CAMERA SDL_SENSOR SDL_GPU SDL_RENDER SDL_OPENGL SDL_OPENGLES SDL_KMSDRM SDL_WAYLAND)
  set(${option} OFF CACHE BOOL "" FORCE)
endforeach()
set(SDL_VIDEO ON CACHE BOOL "" FORCE)
set(SDL_VULKAN ON CACHE BOOL "" FORCE)
set(SDL_X11 ON CACHE BOOL "" FORCE)
set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
add_subdirectory("${OW_sdl_SOURCE}" "${CMAKE_CURRENT_BINARY_DIR}/third_party/SDL" EXCLUDE_FROM_ALL)
add_library(ow_render STATIC src/render_vulkan.cpp)
target_include_directories(ow_render PUBLIC include)
target_include_directories(ow_render SYSTEM PRIVATE "${OW_vulkan_headers_SOURCE}/include")
target_link_libraries(ow_render PUBLIC ow_presentation PRIVATE SDL3::SDL3-static)
ow_native_policy(ow_render)
target_link_libraries(omniweft_examples PRIVATE ow_render)
target_compile_definitions(omniweft_examples PRIVATE OW_ENABLE_VULKAN=1)
