# SPDX-License-Identifier: Apache-2.0
file(READ "${CMAKE_CURRENT_LIST_DIR}/../toolchains/bootstrap.json" bootstrap_pins)
if(WIN32 AND CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
  string(JSON expected_compiler GET "${bootstrap_pins}" compilers windows version)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  string(JSON expected_compiler GET "${bootstrap_pins}" compilers linux version)
else()
  message(FATAL_ERROR "Unsupported bootstrap compiler/OS. Use x64 MSVC on Windows or clang++-18 on Linux; see toolchains/bootstrap.json.")
endif()
if(NOT CMAKE_CXX_COMPILER_VERSION VERSION_EQUAL expected_compiler)
  message(FATAL_ERROR "Compiler pin mismatch: found ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}, require ${expected_compiler}. Install/select the pinned toolchain; servicing changes require a reviewed pin update.")
endif()
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
  message(FATAL_ERROR "The bootstrap requires a 64-bit compiler. Select x64 build tools.")
endif()
if(NOT CMAKE_GENERATOR STREQUAL "Ninja")
  message(FATAL_ERROR "Use the Ninja generator through the headless CMake presets.")
endif()
execute_process(COMMAND "${CMAKE_MAKE_PROGRAM}" --version
  OUTPUT_VARIABLE ninja_version OUTPUT_STRIP_TRAILING_WHITESPACE
  RESULT_VARIABLE ninja_result)
string(JSON expected_ninja GET "${bootstrap_pins}" ninja_executable_version)
if(NOT ninja_result EQUAL 0 OR NOT ninja_version STREQUAL expected_ninja)
  message(FATAL_ERROR "Use pinned Ninja ${expected_ninja}; see toolchains/build-tools.txt. Found '${ninja_version}'.")
endif()
